---
# tasks file for ansible-role-openvpn-client

- include_tasks: deploy-on-host.yml
  when: vpn_client_deploy_on_host|default(False)

# This is a bit more complex but offer better solutions when we want to access
# the server via its EIP. Using the direct above - we will lose the ability to
# access the service exposed via its EIP if the VPN set redirect default gateway to
# the vpn tunnel. We need to use ELB or other nginx to forward the request.

# By using the vpn docker container we wont run into this issue and we can run
# each command that needs the VPN gateway in the container using the docker
# --net=container:<container_name> option.

- include_tasks: deploy-on-docker.yml
  when: vpn_client_deploy_on_docker|default(True)
